---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - apps
  - clusterrolebindings
  - clusterroles
  - deployments
  - pods
  - reviewapps
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - apps
  - clusterrolebindings
  - clusterroles
  - deployments
  - pods
  - reviewapps/finalizers
  - serviceaccounts
  - services
  verbs:
  - update
- apiGroups:
  - '*'
  resources:
  - apps
  - clusterrolebindings
  - clusterroles
  - deployments
  - pods
  - reviewapps/status
  - serviceaccounts
  - services
  verbs:
  - get
  - patch
  - update
