apiVersion: roci.io/v1beta1
kind: Application
metadata:
  name: application-sample
  namespace: roci-test
spec:
  version:
    ui: 0.0.3
    core: 0.0.3
  variables:
    hostUrl: https://1.1.1.1
    coreApiPort: 32100
    coreApiSocketPort: 32101
    uiPort: 32102
    apiUrl: http://localhost:32100
  env:
    - name: DOCKER_USER
      value: test
    - name: DOCKER_PASSWORD
      value: test
    - name: DOCKER_SERVER
      value: test
    - name: POSTGRE_HOST
      value: localhost
    - name: POSTGRE_USERNAME
      value: idalavye
    - name: POSTGRE_PASSWORD
      value: idalavye
    - name: POSTGRE_PORT
      value: 5432
    - name: POSTGRE_DATABASE
      value: postgres
  override:
    deployment:
      spec:
        template:
          spec:
            imagePullSecrets:
              - name: ty-registry-secret
    service:
      metadata:
        annotations:
          consul.hashicorp.com/service-sync: 'true'
  coreDeployment:
    spec:
      replicas: 1
      template:
        metadata:
          annotations:
            roci.io/inject: "true"
            roci.io/authoriazation: "true"
  coreService:
    metadata:
      annotations:
        roci.io/inject: "true"
        roci.io/authoriazation: "true"
  uiService:
    metadata:
      annotations:
        roci.io/inject: "true"
        roci.io/authoriazation: "true"


