apiVersion: roci.io/v1beta1
kind: ReviewApp
version: lib-ui-0.0.5
metadata:
  name: reviewapp-sample
  namespace: roci-test
spec:
  registry:
    ui: registry.company.com/team/rocinante
    core: registry.company.com/team/rocinante
    imagePullSecrets:
      - ty-registry-secrets
  variables:
    coreApiPort: 30001
    coreApiSocketPort: 30002
    uiPort: 30003
    apiUrl: http://localhost:30001
  env:
    - name: DOCKER_USER
      valueFrom:
        secretKeyRef:
          name: docker-credentials
          key: username
    - name: DOCKER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: docker-credentials
          key: password
    - name: DOCKER_SERVER
      valueFrom:
        secretKeyRef:
          name: docker-credentials
          key: server
  override:
    deployment:
      spec:
        template:
          spec:
            imagePullSecrets:
              - name: ty-registry-secret
    service:
      metadata:
        annotations:
          consul.hashicorp.com/service-sync: 'true'
  coreDeployment:
    spec:
      replicas: 1
      template:
        metadata:
          annotations:
            roci.io/inject: "true"
            roci.io/authoriazation: "true"
  coreService:
    metadata:
      annotations:
        roci.io/inject: "true"
        roci.io/authoriazation: "true"
  uiService:
    metadata:
      annotations:
        roci.io/inject: "true"
        roci.io/authoriazation: "true"


