apiVersion: v1
kind: Service
metadata:
  name: <project-name>
  namespace: <project-namespace>
  annotations:
    roci.io/reviewapp: "true"
  labels:
    app: <project-name>
spec:
  selector:
    app: <project-name>
  ports:
    - protocol: TCP
      port: <app-port>
      targetPort: <app-port>
      nodePort: <node-port>
  type: NodePort
