import ThemeProvider from 'theme/ThemeProvider';

import SettingsProvider from 'contexts/settingsContext';

import { AuthProvider } from 'contexts/authContext';

import { inter } from 'utils/font';

import { RTL } from 'components/rtl';

import 'i18n';

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'react-quill/dist/quill.snow.css';
import 'simplebar-react/dist/simplebar.min.css';
import 'pure-react-carousel/dist/react-carousel.es.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { unstable_noStore as noStore } from 'next/cache';

export const metadata = {
  title: 'Review App Dashboard',
  description: 'Generated by Ibrahim Dagdelen and Kader Genc',
};

const RootLayout = async ({ children }) => {
  noStore();
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <SettingsProvider apiUrl={process.env.API_URL}>
          <ThemeProvider>
            <AuthProvider>
              <RTL>{children}</RTL>
              <ToastContainer />
            </AuthProvider>
          </ThemeProvider>
        </SettingsProvider>
      </body>
    </html>
  );
};

export default RootLayout;
